version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:13
    container_name: blog_postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - blog_network

  # Strapi (Backend)
  strapi:
    container_name: blog_strapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./backend:/srv/app
      - strapi_node_modules:/srv/app/node_modules
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    networks:
      - blog_network

  # Next.js (Frontend)
  nextjs:
    container_name: blog_nextjs
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - nextjs_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - blog_network

# Volumes para persistência de dados
volumes:
  postgres_data:
  strapi_node_modules:
  nextjs_node_modules:

# Rede Docker
networks:
  blog_network:
    driver: bridge